### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MichaelM00** [Anmol-Singh-Jaggi/Directory-Snapshot#3]
Thank you for your program @Anmol-Singh-Jaggi

I get the following error on some directories
Traceback (most recent call last):
  File "/directory-snapshot/src/dir_snap.py", line 178, in <module>
    main()
  File "/directory-snapshot/src/dir_snap.py", line 171, in main
    get_snapshot(src_path, dest_path, progress_bar, ignore_hidden, ignore_symlinks, max_rec_depth)
  File "/directory-snapshot/src/dir_snap.py", line 74, in get_snapshot
    if entry.is_dir():
  File "/python3.9/pathlib.py", line 1422, in is_dir
    return S_ISDIR(self.stat().st_mode)
  File "/python3.9/pathlib.py", line 1221, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '/var/sysfile'

The error causes the program to stop.

I also thought of some enhancements that could make this useful program even better

1. Flags to add additional attributes about directories and files in HTML such as created time, modified time, real modified time, extension type, hash of file (CRC/MD5/SHA) etc.
2. Possibility to arrange HTML file layout such as putting Directories header items before Files header items, removing specific header items and ability to sort HTML columns by file name, file size etc. in ascending or descending order
3. Is it possible to add hardlinks items?
4. Dark layout for HTML

Thank you again!

**Comment by Anmol-Singh-Jaggi** [comment]
Have fixed the bug. Let me know if you still face it.
Have also refactored the code to make it easier to understand.

Regarding improvements:
1. In progress.
2. In progress.
3. [A bit tricky](https://stackoverflow.com/a/61281080/1925388).
4. There is an extension [Dark Reader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=en) that automatically enables dark theme on every website. I have been using it since quite some time now myself.

**Comment by MichaelM00** [comment]
Thanks @Anmol-Singh-Jaggi. Did a quick test and it seems to work now without stopping. The program output is more verbose now, I wonder if there could be a flag to make it quieter?

While using the program I realized that an exclude option (excluding directories/files based on pattern or path) would be quite useful. Some directories can be really deep/contain many files and take a long time to run and some may not be needed/wanted to be kept in the final HTML output. 

Also looking forward to the improvements! Please let me know if there is anything I can help test for you.

3. It does seem tricky..also the question of detection across platforms (by the way is it right to assume the current symlinks detection works across common platforms/filesystems?) 
4. Yup I do know the extension, but sometimes on larger pages there can be high CPU usage/freezing issues. More problematic is that some browsers have started locking down/disallowed running extensions on local files and some of them (though mainly mobile) don't support extensions. There are some workarounds but it would be nice if there was a native dark theme.

**Comment by Anmol-Singh-Jaggi** [comment]
1. Will add a flag to set the logging level from command line.
2. Will add an option to exclude entries based on pattern.
3. Symlink detection should work on all platforms assuming Python devs have implemented it correctly. I am only able to test it on macOS for now.
4. Am not an expert on CSS, but will try add native dark theme support. Feel free to suggest the CSS to use for this if you have ideas.

**Comment by MichaelM00** [comment]
There's a few ways to style the theme according to the user's preference on the page itself which would be nice but as far as I know most of them require some Javascript and/or newer browser features which might not be ideal to work on some browsers. I did find one way to achieve this with just CSS, example:


```
<body>
<input type="radio" name="theme" value="light" checked="checked">Light Theme<br>
<input type="radio" name="theme" value="dark">Dark Theme<br>
<style>
	input[type=radio][value=light]:checked ~ table {
		color: #252525;
		background-color: #F1F1F1;
	}
	
	input[type=radio][value=dark]:checked ~ table {
		color: #9E9E9E;
		background-color: #0F0F0F;
	}
</style>
...
...
```

It is basic and less flexible compared to some other solutions but it might work for us here. Just need to figure out the best way to apply this properly to all page elements.
